//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasport
    {
        public int ID_Pasporta { get; set; }
        public string Seria { get; set; }
        public string Nomer { get; set; }
        public System.DateTime Data_vidachi { get; set; }
        public string Kod_podrazdelenia { get; set; }
    }
}
