//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podrazdelenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Podrazdelenia()
        {
            this.Sotrudniki = new HashSet<Sotrudniki>();
            this.Zajavki = new HashSet<Zajavki>();
        }
    
        public int ID_Podrazdelenia { get; set; }
        public string Nazvanie_goroda { get; set; }
        public string Nazvanie_ylici { get; set; }
        public int Nomer_stroenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrudniki> Sotrudniki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zajavki> Zajavki { get; set; }
    }
}
