//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public int ID_Sotrudnika { get; set; }
        public int ID_Dolzhnosti { get; set; }
        public Nullable<int> ID_Podrazdelenia { get; set; }
        public string Familia { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public string Seria_pas { get; set; }
        public string Nomer_pas { get; set; }
        public string Kod_avtorizacii { get; set; }
    
        public virtual Dolzhnosti Dolzhnosti { get; set; }
        public virtual Podrazdelenia Podrazdelenia { get; set; }
    }
}
