//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zajavki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zajavki()
        {
            this.GrupZajavki = new HashSet<GrupZajavki>();
        }
    
        public int ID_Zajavki { get; set; }
        public string Nomer_zajavki { get; set; }
        public int ID_Polzovatelia { get; set; }
        public int ID_Podrazdelenia { get; set; }
        public System.DateTime Data_poseshenia { get; set; }
        public Nullable<System.DateTime> Data_oformlenia { get; set; }
        public int ID_Celi { get; set; }
        public int ID_Statusa { get; set; }
        public string Soobshenie { get; set; }
    
        public virtual Celi Celi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupZajavki> GrupZajavki { get; set; }
        public virtual Podrazdelenia Podrazdelenia { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
        public virtual Statusi Statusi { get; set; }
    }
}
